version: '3'
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - ".env"
    command: [
      '--wait_timeout=360000'
    ]
    environment:
      - MARIADB_DATABASE=mysql
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASS}
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - ./server/inc/databases:/var/lib/mysql
      - ./server/inc/my.cnf:/etc/mysql/my.cnf:ro
      - ./server/inc/innodb.cnf:/etc/mysql/conf.d/innodb.cnf:ro

networks: # Required for connectivity with separate docker-compose web framework
  default:
    name: database
